name: ci-cd-lambda-java

on:
  push:
    branches:
      - develop
      - main
      - 'release/**'
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # necesario para OIDC

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1  # cambia si usas otra

      - name: ¿Quién soy en AWS?
        run: aws sts get-caller-identity

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar y testear
        run: mvn -B -ntp clean verify

      - name: Instalar SAM CLI
        run: pip install aws-sam-cli

      - name: SAM validate (lint)
        run: sam validate --lint

      - name: Comprobar artefacto
        run: |
          ls -lah target
          test -f target/app.jar && echo "JAR OK" || (echo "FALTA target/app.jar" && exit 1)


      - name: SAM deploy (dev)
        run: |
          sam deploy \
            --no-build \  
            --stack-name audio2text-lambda \
            --template-file template.yaml \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset \
            --parameter-overrides Env=dev FunctionName=audio2text-lambda \
            --resolve-s3 \
            --confirm-changeset
