name: Deploy Lambda

on:
  push:
    branches:
      - main   # despliega cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'                # usa la versi√≥n de Java que uses
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Install AWS CLI
        uses: aws-actions/setup-cli@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment zip
        run: |
          mkdir -p build
          cp target/audio2text-lambda-1.0-SNAPSHOT.jar build/
          cd build
          zip function.zip audio2text-lambda-1.0-SNAPSHOT.jar

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name audio2text-lambda-dev \
            --zip-file fileb://build/function.zip
